version: "3"
services:
  postgres:
    container_name: bitecritic-db
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/db/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
